package javainicial;
import java.util.Scanner;
/*	24/04/2019 - 11:05
 *  URI -Lucca BM
 *  GITHUB - github.com/LuccaBM73/
 *  
 */
public class Aula1 
{
	public static void main(String[] args) 
	{
		Scanner input = new Scanner(System.in);
		int A = input.nextInt();
		int B = input.nextInt();
		float C = input.nextFloat();
		float SALARY = A*C;
		System.out.println("NUMBER = "+A);
		System.out.printf("\nSALARY = U$ "+ SALARY);
		
		
		
		
	}
	
	
}
